language: node_js
node_js:
  - node

script:
  - npm install -g serverless
  - npm install
  - sls deploy

branches:
  only:
    - develop
    - serverless-reset

cache:
  directories:
    - "node_modules"
