language: node_js
node_js:
  - node

install:
  - pip install --user awscli

script:
  - npm install -g serverless
  - npm install
  - sls deploy

branches:
  only:
    - develop

cache:
  directories:
    - "node_modules"
