language: node_js
node_js:
  - node

install:
  - pip install --upgrade pip
  - pip install --user awscli

script:
  - npm install -g serverless
  - npm install
  - aws s3 cp s3://dot-env/api.valeriehudak.com-env.dev .env
  - sls deploy

branches:
  only:
    - develop
    - serverless-reset

cache:
  directories:
    - "node_modules"
