version: 2

jobs:
  build:
    docker:
      - image: circleci/php:7.1.8-browsers
    working_directory: ~/laravel
    steps:
      - checkout
      - run: wget http://ftp.ruby-lang.org/pub/ruby/2.4/ruby-2.4.2.tar.gz
      - run: tar -xzvf ruby-2.4.2.tar.gz
      - run: cd ruby-2.4.2/
      - run: ./configure
      - run: make
      - run: sudo make install
      - run: cd ..
#      - run: gem install eb_deployer
      - run: sudo composer self-update
#      - restore_cache:
#          keys:
#            - composer-v1-{{ checksum "composer.json" }}
#            - composer-v1-
      - run: composer install -n --prefer-dist
#      - save_cache:
#          key: composer-v1-{{ checksum "composer.json" }}
#          paths:
#            - vendor
#      - run: touch storage/testing.sqlite
#      - run: php artisan migrate --env=testing --database=sqlite_testing --force
      - run: curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
      - run: unzip awscli-bundle.zip
      - run: sudo ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws
      - run: aws s3 cp s3://api.valeriehudak-com.config/env.dev ./.env
      - run: ./vendor/bin/phpunit
