version: 2

jobs:
  build:
    docker:
      - image: circleci/php:7.1.8-browsers
      - image: ruby:2.3.1
    working_directory: ~/laravel
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt install -y zlib1g-dev build-essential libssl-dev libreadline-dev libyaml-dev libsqlite3-dev sqlite3 libxml2-dev libxslt1-dev libcurl4-openssl-dev python-software-properties libffi-dev nodejs
      - run: git clone https://github.com/rbenv/rbenv.git ~/.rbenv
      - run: echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bashrc
      - run: echo 'eval "$(rbenv init -)"' >> ~/.bashrc
      - run: git clone https://github.com/rbenv/ruby-build.git ~/.rbenv/plugins/ruby-build
      - run: echo 'export PATH="$HOME/.rbenv/plugins/ruby-build/bin:$PATH"' >> ~/.bashrc
      - run: rbenv install 2.4.2
      - run: rbenv global 2.4.2
      - run: ruby -v
#      - run: gem install eb_deployer
      - run: sudo composer self-update
#      - restore_cache:
#          keys:
#            - composer-v1-{{ checksum "composer.json" }}
#            - composer-v1-
      - run: composer install -n --prefer-dist
#      - save_cache:
#          key: composer-v1-{{ checksum "composer.json" }}
#          paths:
#            - vendor
#      - run: touch storage/testing.sqlite
#      - run: php artisan migrate --env=testing --database=sqlite_testing --force
      - run: curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
      - run: unzip awscli-bundle.zip
      - run: sudo ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws
      - run: aws s3 cp s3://api.valeriehudak-com.config/env.dev ./.env
      - run: ./vendor/bin/phpunit
