version: 2

jobs:
  build:
    docker:
      - image: circleci/php:7.1.8-browsers
    working_directory: ~/laravel
    steps:
      - checkout
      - run:
        name: install ruby
        command: |
          sudo apt-get update
          sudo apt-get install -y git-core curl zlib1g-dev build-essential libssl-dev libreadline-dev libyaml-dev libsqlite3-dev sqlite3 libxml2-dev libxslt1-dev libcurl4-openssl-dev python-software-properties libffi-dev nodejs
          sudo apt-get install -y libgdbm-dev libncurses5-dev automake libtool bison libffi-dev
          gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
          curl -sSL https://get.rvm.io | bash -s stable
          source ~/.rvm/scripts/rvm
          rvm install 2.4.2
          rvm use 2.4.2 --default
          ruby -v
#      - run: gem install eb_deployer
      - run: sudo composer self-update
#      - restore_cache:
#          keys:
#            - composer-v1-{{ checksum "composer.json" }}
#            - composer-v1-
      - run: composer install -n --prefer-dist
#      - save_cache:
#          key: composer-v1-{{ checksum "composer.json" }}
#          paths:
#            - vendor
#      - run: touch storage/testing.sqlite
#      - run: php artisan migrate --env=testing --database=sqlite_testing --force
      - run: curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
      - run: unzip awscli-bundle.zip
      - run: sudo ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws
      - run: aws s3 cp s3://api.valeriehudak-com.config/env.dev ./.env
      - run: ./vendor/bin/phpunit
