version: 2

jobs:
  build:
    docker:
      - image: circleci/php:7.1.8-browsers
    working_directory: ~/laravel
    steps:
      - checkout
      - run: sudo apt-get install -y ruby-full
      - run: sudo gem install eb_deployer
      - run: sudo composer self-update
      - run: composer install -n --prefer-dist
      - run: curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
      - run: unzip awscli-bundle.zip
      - run: sudo ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws
      - run: aws s3 cp s3://api.valeriehudak-com.config/env.dev ./.env
      - run: ./vendor/bin/phpunit
      - deploy:
          name: EB Deployer
          command: |
            if [ "${CIRCLE_BRANCH}" == "develop" ]; then
              ./artisan eb:deploy
            else
              echo "Not develop branch so not deploying"
            fi
  deployment:
    docker:
      - image: circleci/php:7.1.8-browsers
      working_directory: ~/laravel
      steps:
        - checkout
